### ISSUE TITLE
TypeError when no SiteLanguage was resolved

### ISSUE THREAD

**Issue by garfieldius** [b13/justincase#18]
If the router did not resolve a SiteLanguage for the current Site, the call of `$site->getRouter()->matchRequest($request, $previousResult);` in `\B13\JustInCase\Middleware\LowerCaseUri::process` will cause a TypeError in `\TYPO3\CMS\Core\Routing\PageRouter::matchRequest` in TYPO3 11.5.30.

### How to reproduce

Have a site with one or more langage, but no language has an empty, or just a slash, as slug as entry. Similar to this site config:

```yaml
base: 'https://my.site/'

languages:
  - title: English
    languageId: 0
    base: /en
    # ....
  - title: Italian
    languageId: 1
    base: /it
    # ...
```

Now call an URL without any of those prefixes, eg. https://my.site/not/existing/site.

The expected behaviour would be a 404 page, instead a 503 error and message is shown.

### Possible fix

When changing the lines

```php
$site->getRouter()->matchRequest($request, $previousResult);
return $handler->handle($request);
```
in `\B13\JustInCase\Middleware\LowerCaseUri::process` to

```php
if ($previousResult->getLanguage()) {
    $site->getRouter()->matchRequest($request, $previousResult);
}

return $handler->handle($request);
```

It works as expected. Also the lowercase redirects work for URLs with a prefix.
